@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTc4OTAyNTI2OSwiZXhwIjoxNzg5MDMyNDY5fQ.y1pe1apOJZArThlhaLsY_LtFXUDhJGHiyDkDB1jht00

###
GET {{baseUrl}}/products

### GET ONE
GET {{baseUrl}}/products/8

###
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Producto 1",
  "price": 0,
  "stock": 0,
  "categoryId": 1
}

###
PATCH {{baseUrl}}/products/8
Content-Type: application/json

{
  "name": "Producto 1 - Updated",
  "price": 100,
  "stock": 10,
  "categoryId": 2
}

###
DELETE {{baseUrl}}/products/7

### Test Ruta 2
POST {{baseUrl}}/products/ruta2

### AUTH
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}